### ISSUE TITLE
Move to stumpwm organization?

### ISSUE THREAD

**Issue by dmb2** [stumpwm/SDB#1]
Are you open to moving this to the main stumpwm organization?

**Comment by szos** [comment]
I would be happy to! I have some requests about the moving: 

- I would like to continue being (one of) the maintainers of the software. I dont know the best way to do that as Im not familiar with github, but Id imagine it wouldnt be to difficult. 
- Id like to wait until after the holidays to do the move. 

I also would like to do some more testing and put in the most recent version of mcclim that is known to function with SDB (ive had some issues with updates breaking things before), but that can happen after the move.

**Comment by szos** [comment]
Ok now that the holidays are over I have a little time to put towards this and can discuss better what to do/how to approach this. 

Im also going to get started cleaning up the code and making it more accessible. 

Let me know how youd like to move forward

**Comment by dmb2** [comment]
I think you initiate the transfer:
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by szos** [comment]
Thank you for the link and the invitation to the organization! It seems that I need to have permission to create a repo in the stumpwm org in order to transfer ownership, which I don't think I have. Once I have that permission I'll transfer ownership.

**Comment by dmb2** [comment]
Try again, I enabled repo creation for members.

**Comment by szos** [comment]
Wonderful! The repo has been transfered to be under the Stupmwm organization :)
